paths:
  parsed_data_path: ./output/parsed_data_signal_wminush
  im_arrays_path: ./output/im_arrays
  im_arrays_processed_path: ./output/im_arrays_processed
  histograms_path: ./output/histograms
  metadata_cache_path: ./output/metadata_cache_signal_wminush.json
  jobs_logs_path: ./output/logs_signal_wminush
names:
  run_name: cms_hgg_signal_wminush
  histogram_filename: cms_hgg_signal.root
run_metadata:
  run_name: cms_hgg_signal_wminush
  base_output_dir: /storage/agrp/berkom/atlas-utilization/output/cms_hgg_signal_wminush
  batch_job_index: null
  total_batch_jobs: null
tasks:
  do_parsing: true
  do_mass_calculating: false
  do_post_processing: false
  do_histogram_creation: false
testing_config:
  is_on: false
  test_run_index: null
  testing_jobs_path: ./testing_jobs
  limit_files_per_year: null
  limit_combinations: null
parsing_task_config:
  output_path: ./output/parsed_data_signal_wminush
  file_urls_path: ./output/metadata_cache_signal_wminush.json
  jobs_logs_path: ./output/logs_signal_wminush
  release_years: []
  specific_record_ids:
  - 70173
  parse_mc: true
  use_multiprocessing: false
  parallel_processes: 4
  threads: 8
  env_threshold_memory_mb: 8000
  chunk_yield_threshold_bytes: 2147483648
  count_retries_failed_files: 3
  fetching_metadata_timeout: 60
  max_files_to_process: null
  possible_data_tree_names:
  - Events
  - CollectionTree
  create_dirs: true
  show_progress_bar: true
  trigger_requirements:
    mode: any
    paths:
    - HLT_Diphoton30_18_R9Id_OR_IsoCaloId_AND_HE_R9Id_Mass90
  read_pileup_info: true
  read_event_weights: true
  extra_object_fields:
    Photons:
    - electronVeto
    - mvaID_WP90
    - isScEtaEB
    - isScEtaEE
    - r9
    - hoe
    - sieie
    - pfRelIso03_all
    - pfRelIso03_chg
    - mvaID
    - cutBased
    - pixelSeed
  particle_counts:
    photons:
      min: 2
      max: 20
  kinematic_cuts:
    photons:
      pt:
        min: 20.0
      bool_require:
      - electronVeto
      - mvaID_WP90
      bool_any_of:
      - isScEtaEB
      - isScEtaEE
